Screen:

    MDRectangleFlatButton:
        text: "Light Button"
        pos_hint: {"center_x": .5, "center_y": .7}
        md_bg_color: app.theme_cls.primary_light
    MDRaisedButton:
        text: "Second Button"
        pos_hint: {"center_x": .5, "center_y": .5}
    MDRaisedButton:
        text: "DarkButton"
        pos_hint: {"center_x": .5, "center_y": .3}
        md_bg_color: app.theme_cls.primary_dark