<MDRoundFlatButton>:

Screen:

    MDCard:
        size_hint: None,None
        size: 800,1000
        pos_hint: {"center_x": .5, "center_y": .5}
        elevation: 10 #Shadow
        padding: ('25dp', '25dp', '25dp', '25dp')
        spacing:40
        orientation: 'vertical'
        MDLabel:
            id:Data_input_label
            text: "Datos de Entrada"
            font_size: 40
            halign: "center"
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 15
        MDTextField:
            id:user #Temperatura --> variable?
            hint_text: "Temperatura de entrada (°C)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "thermometer-low"
            icon_right_color_focus: "orange"
        MDTextField:
            id:password #presion --> variable?
            hint_text: "Presión de entrada (KPa)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "eye-off"
            icon_right_color_focus: "orange"
        MDTextField:
            id:password #presion --> variable?
            hint_text: "Presión extraccion (KPa)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "eye-off"
            icon_right_color_focus: "orange"
        MDTextField:
            id:password #presion --> variable?
            hint_text: "Presión en el condensador (KPa)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "eye-off"
            icon_right_color_focus: "orange"
        MDTextField:
            id:password #presion --> variable?
            hint_text: "Eficiancia de la bomba (%)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "percent-outline"
            icon_right_color_focus: "orange"
        MDTextField:
            id:password #presion --> variable?
            hint_text: "Eficiencia de la turbina (%)"
            mode: "round"
            max_text_length: 15
            helper_text: "Massage"
            icon_right: "percent-outline"
            icon_right_color_focus: "orange"
        BoxLayout:
            orientation: 'horizontal'
            spacing: 10  # Espacio entre los botones

            MDRoundFlatButton:
                text: "Calcular"
                font_size: 20
                size_hint_x: 0.4
                #on_press: app.login()

            MDRoundFlatButton:
                text: "Clear"
                font_size: 20
                size_hint_x: 0.4
                #on_press: app.clear()

